name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3 # Actualizado a la versión más reciente

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v3 # Actualizado a la versión más reciente
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3 # Actualizado a la versión más reciente
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v3 # Actualizado a la versión más reciente
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
